# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Options.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from AccountDetails import Ui_AccountsMainWindow

class Ui_MainWindow(object):
    def click_account(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AccountsMainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 120, 551, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(28)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAccount = QtWidgets.QAction(MainWindow)
        self.actionAccount.setObjectName("actionAccount")
        self.actionAccount.triggered.connect(self.click_account)
        self.actionPlace_an_order = QtWidgets.QAction(MainWindow)
        self.actionPlace_an_order.setObjectName("actionPlace_an_order")
        self.actionCart = QtWidgets.QAction(MainWindow)
        self.actionCart.setObjectName("actionCart")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuOptions.addAction(self.actionAccount)
        self.menuOptions.addAction(self.actionPlace_an_order)
        self.menuOptions.addAction(self.actionCart)
        self.menuOptions.addAction(self.actionExit)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Store"))
        self.label.setText(_translate("MainWindow", "Welcome to the Store. Happy Shopping!"))
        self.label.adjustSize()
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionAccount.setText(_translate("MainWindow", "Account"))
        self.actionPlace_an_order.setText(_translate("MainWindow", "Place an order"))
        self.actionCart.setText(_translate("MainWindow", "Cart"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X"))

        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
