# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_6.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import pyodbc

conn = pyodbc.connect('DRIVER={SQL SERVER};SERVER=LAPTOP-F8010458\SQLEXPRESS;DATABASE=warehouse;Trusted_connection=yes')

class Ui_window_6(object):
    def __init__(self, note1, note2):
        self.note1 = note1
        self.note2 = note2
    
    def setupUi(self, window_6):
        window_6.setObjectName("window_6")
        window_6.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(window_6)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        font.setItalic(True)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(510, 80, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 150, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 153, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 230, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(550, 245, 111, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 350, 121, 31))
        self.pushButton.setObjectName("pushButton")
        window_6.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window_6)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        window_6.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window_6)
        self.statusbar.setObjectName("statusbar")
        window_6.setStatusBar(self.statusbar)

        self.retranslateUi(window_6)
        QtCore.QMetaObject.connectSlotsByName(window_6)

        self.pushButton.clicked.connect(self.payment)

    def retranslateUi(self, window_6):
        _translate = QtCore.QCoreApplication.translate
        window_6.setWindowTitle(_translate("window_6", "Payment"))
        self.label.setText(_translate("window_6", "Payment"))
        self.label_2.setText(_translate("window_6", "Thank you for shopping with us"))
        self.label_2.adjustSize()
        self.label_3.setText(_translate("window_6", self.note1))
        self.label_3.adjustSize()
        self.label_4.setText(_translate("window_6", "Total Amount to PAY :"))
        self.label_4.adjustSize()

        cursor = conn.cursor()
        cursor.execute('select Total_Amount from cart')
        self.total = 0
        for i in cursor:
            self.total += i[0]
        
        self.label_5.setText(_translate("window_6", str(self.total)))
        self.label_5.adjustSize()
        self.label_6.setText(_translate("window_6", "Please select the mode of Payment :"))
        self.label_6.adjustSize()
        self.comboBox.setItemText(0, _translate("window_6", "Google Pay"))
        self.comboBox.setItemText(1, _translate("window_6", "Phone Pe"))
        self.comboBox.setItemText(2, _translate("window_6", "Paytm"))
        self.comboBox.setItemText(3, _translate("window_6", "Mobiwiki"))
        self.comboBox.setItemText(4, _translate("window_6", "Cash on Delivery"))
        self.pushButton.setText(_translate("window_6", "Proceed to Pay"))
        

    def payment(self):
        msg = QMessageBox()
        msg.setWindowTitle("Confirm")
        msg.setText("Do you want to complete payment?")
        msg.setIcon(QMessageBox.Question)
        msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)

        msg.buttonClicked.connect(self.popup_button)
        x = msg.exec_()
    

    def popup_button(self, i):
        cursor = conn.cursor()
        cursor.execute('select Phone_No from payment')
        count = 0
        for i in cursor:
            if i[0] == self.note2:
                count+=1
        mode = self.comboBox.currentText()
        if count == 0:
            cursor = conn.cursor()
            cursor.execute('insert into payment(Name, Phone_No, Total_Amount, Mode_of_Payment, Payment_Status) values(?,?,?,?,?)',(self.note1,self.note2,self.total,mode,i.text(),))
            conn.commit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window_6 = QtWidgets.QMainWindow()
    ui = Ui_window_6()
    ui.setupUi(window_6)
    window_6.show()
    sys.exit(app.exec_())
