# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from window_4 import Ui_InventoryStock
import pyodbc
from window_5 import Ui_window_5
from window_6 import Ui_window_6

conn = pyodbc.connect('DRIVER={SQL SERVER};SERVER=LAPTOP-F8010458\SQLEXPRESS;DATABASE=warehouse;Trusted_connection=yes')
class Ui_StoreMainPage(object):
    def __init__(self, message1, message2):
        self.message1 = message1
        self.message2 = message2
        
    def setupUi(self, StoreMainPage):
        StoreMainPage.setObjectName("StoreMainPage")
        StoreMainPage.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(StoreMainPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 60, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(22)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 190, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 240, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 290, 121, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 340, 121, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        StoreMainPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StoreMainPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        StoreMainPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StoreMainPage)
        self.statusbar.setObjectName("statusbar")
        StoreMainPage.setStatusBar(self.statusbar)

        self.retranslateUi(StoreMainPage)
        QtCore.QMetaObject.connectSlotsByName(StoreMainPage)

    def retranslateUi(self, StoreMainPage):
        _translate = QtCore.QCoreApplication.translate
        StoreMainPage.setWindowTitle(_translate("StoreMainPage", "Store Main Page"))
        self.label.setText(_translate("StoreMainPage", "Hi"))
        self.label.adjustSize()
        self.label_2.setText(_translate("StoreMainPage", self.message1))
        self.label_2.adjustSize()
        self.label_3.setText(_translate("StoreMainPage", "Welcome to our Store"))
        self.label_3.adjustSize()
        self.label_4.setText(_translate("StoreMainPage", "How can we help you?"))
        self.label_4.adjustSize()
        self.pushButton.setText(_translate("StoreMainPage", "Place an Order"))
        self.pushButton.adjustSize()
        self.pushButton.clicked.connect(self.PlaceOrder)
        self.pushButton_2.setText(_translate("StoreMainPage", "View Cart"))
        self.pushButton_2.adjustSize()
        self.pushButton_2.clicked.connect(self.ViewCart)
        self.pushButton_3.setText(_translate("StoreMainPage", "Make Payment"))
        self.pushButton_3.adjustSize()
        self.pushButton_3.clicked.connect(self.MakePayment)
        self.pushButton_4.setText(_translate("StoreMainPage", "Exit"))
        self.pushButton_4.adjustSize()
        self.pushButton_4.clicked.connect(self.exit)

    def PlaceOrder(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_InventoryStock()
        self.ui.setupUi(self.window)
        self.window.show()

    def ViewCart(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_window_5()
        self.ui.setupUi(self.window)
        self.window.show()

    def MakePayment(self):
        self.window = QtWidgets.QMainWindow()
        self.note1 = self.message1
        self.note2 = self.message2
        self.ui = Ui_window_6(self.note1, self.note2)
        self.ui.setupUi(self.window)
        self.window.show()

    def exit(self):
        cursor = conn.cursor()
        cursor.execute('truncate table cart;')
        conn.commit()
        StoreMainPage.close()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StoreMainPage = QtWidgets.QMainWindow()
    ui = Ui_StoreMainPage()
    ui.setupUi(StoreMainPage)
    StoreMainPage.show()
    sys.exit(app.exec_())
